import { useState } from 'react';
import { ArrowUpRight, BadgeCheck, Bell, Check, ClipboardCheck, LayoutDashboard, Package, ShieldCheck } from 'lucide-react';
import ProductAwareScan from './ProductAwareScan';
import CompanyReportList from './CompanyReportList';
import MatchingProductCatalog from './MatchingProductCatalog';

type User = { name: string; orgId: string };
export default function FreshCompanyDashboard({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [scan, setScan] = useState(false);
  const [products, setProducts] = useState(false);
  if (scan) return <main className="main-content"><div className="page-wrap"><button className="button ghost" onClick={() => setScan(false)}>Back to company dashboard</button><ProductAwareScan onComplete={() => setScan(false)} /></div></main>;
  if (products) return <main className="main-content"><div className="page-wrap"><button className="button ghost" onClick={() => setProducts(false)}>Back to company dashboard</button><MatchingProductCatalog user={user} /></div></main>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={21} /></div><div><strong>metro-check</strong><span>LEGAL METROLOGY / INDIA</span></div></div><div className="workspace-switcher"><span className="avatar small">{user.name.slice(0, 2).toUpperCase()}</span><div><b>{user.name}</b><small>Company account</small></div></div><nav><div className="nav-item active"><LayoutDashboard size={18} /><span>Company dashboard</span></div><button className="nav-item" onClick={() => setProducts(true)}><Package size={18} /><span>Product register</span></button><button className="nav-item" onClick={onLogout}><ArrowUpRight size={18} /><span>Sign out</span></button></nav></aside><main className="main-content"><header className="topbar"><div className="crumb"><span>Metro-Check</span><b>Company dashboard</b></div><div className="top-actions"><Bell size={18} /><div className="avatar">{user.name.slice(0, 2).toUpperCase()}</div></div></header><div className="page-wrap"><section className="page"><div className="page-heading"><div><span className="eyebrow">COMPANY PORTAL / FRESH WORKSPACE</span><h1>Start with a clean register.</h1></div><div className="page-actions"><button className="button ghost" onClick={() => setProducts(true)}><Package size={17} /> Product register</button><button className="button primary" onClick={() => setScan(true)}><ClipboardCheck size={17} /> Start self-check</button></div></div><div className="signal-band"><div><span className="eyebrow">NO REGISTERED DATA</span><h2>Your compliance workspace is ready.</h2><p>Register a product with its official declarations before scanning labels.</p></div><div className="signal-number"><strong>0</strong><span>products registered</span></div></div><div className="metric-grid"><div className="metric"><div className="metric-icon neutral"><Package /></div><span>Registered products</span><strong>0</strong><small>No products registered</small></div><div className="metric"><div className="metric-icon positive"><ClipboardCheck /></div><span>Self-checks completed</span><strong>0</strong><small>No self-checks yet</small></div><div className="metric"><div className="metric-icon alert"><BadgeCheck /></div><span>Open officer flags</span><strong>0</strong><small>No open flags</small></div><div className="metric"><div className="metric-icon positive"><Check /></div><span>Average score</span><strong>—</strong><small>No inspections yet</small></div></div><section className="panel empty-workspace"><Package size={30} /><h3>No products registered yet</h3><p>Use Product register to save official declaration values before scanning labels.</p><button className="button primary" onClick={() => setProducts(true)}><Package size={16} /> Open product register</button></section><CompanyReportList user={user} /></section></div></main></div>;
}
