import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowUpRight, BarChart3, Bell, Check, ChevronRight, ClipboardCheck, FileText, LayoutDashboard, Package, ShieldCheck, Upload } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import ProductAwareScan from './ProductAwareScan';
import CompanyReportList from './CompanyReportList';
import MatchingProductCatalog from './MatchingProductCatalog';

type User = { name: string; orgId: string; token?: string };
type CheckResult = { fieldName: string; label: string; detectedValue: string | null; isCompliant: boolean; ruleSection: string; confidenceNote: string };
type Inspection = { id: string; product: string; productId?: string; status: string; score: number; createdAt: string; checks: CheckResult[]; summary?: { passed: number; total: number }; report?: { downloadUrl: string } };
type Product = { id: string; name: string; category: string; status: string; declaredMrp?: number; declaredNetQuantity?: number; declaredNetUnit?: string };
type Dashboard = { company: string; products: Product[]; inspections: Inspection[]; flagged: Inspection[]; metrics: { productCount: number; complianceRate: number; inspectionCount: number; openCases: number }; notifications: Array<{ id: string; title: string; text: string; when: string; read: boolean }>; reports: Array<{ id: string; productName: string; verdict: string; score: number; generatedAt: string; downloadUrl: string }>; failedChecks: Array<{ label: string; ruleSection: string; inspectionId: string; product: string; createdAt: string }> };
type Analytics = { trend: Array<{ week: string; value: number }>; failures: Array<{ label: string; value: number }> };

async function request<T>(url: string, options?: RequestInit) {
  const headers = new Headers(options?.headers); const token = localStorage.getItem('metro-check-token');
  if (token && !headers.has('Authorization')) headers.set('Authorization', `Bearer ${token}`);
  const response = await fetch(url, { ...options, headers }); const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.message ?? 'Request failed'); return body as T;
}

export default function FreshCompanyDashboard({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [analytics, setAnalytics] = useState<Analytics>({ trend: [], failures: [] });
  const [screen, setScreen] = useState<'home' | 'products' | 'scan'>('home'); const [selected, setSelected] = useState<Inspection | null>(null); const [resubmitProductId, setResubmitProductId] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [summary, trend] = await Promise.all([request<Dashboard>('/api/company/dashboard'), request<Analytics>('/api/company/analytics')]); setDashboard(summary); setAnalytics(trend); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to load company workspace'); } };
  useEffect(() => { void load(); }, []);
  if (!dashboard) return <main className="main-content"><div className="page-wrap"><section className="page"><div className="panel"><h2>Loading company workspace...</h2>{error && <div className="error-banner"><AlertTriangle size={16} /> {error}</div>}</div></section></div></main>;
  if (screen === 'products') return <Shell user={user} onLogout={onLogout} active="products" onNavigate={setScreen}><MatchingProductCatalog user={user} onChanged={load} /></Shell>;
  if (screen === 'scan') return <Shell user={user} onLogout={onLogout} active="scan" onNavigate={setScreen}><ProductAwareScan onComplete={(inspection: Inspection) => { setSelected(inspection); setScreen('home'); setResubmitProductId(''); void load(); }} companyProductMode initialProductId={resubmitProductId} /></Shell>;
  const recent = dashboard.inspections.slice(0, 5);
  return <Shell user={user} onLogout={onLogout} active="home" onNavigate={setScreen}><section className="page">
    <div className="page-heading"><div><span className="eyebrow">COMPANY PORTAL / {dashboard.company.toUpperCase()}</span><h1>Keep every label ready for market.</h1></div><div className="page-actions"><button className="button ghost" onClick={() => setScreen('products')}><Package size={16} /> Product register</button><button className="button primary" onClick={() => setScreen('scan')}><ClipboardCheck size={16} /> New self-check</button></div></div>
    {error && <div className="error-banner"><AlertTriangle size={16} /> {error}</div>}{selected && <InspectionResult inspection={selected} onClose={() => setSelected(null)} />}
    <div className="signal-band"><div><span className="eyebrow">COMPANY COMPLIANCE</span><h2>{dashboard.metrics.openCases ? `${dashboard.metrics.openCases} product${dashboard.metrics.openCases > 1 ? 's need' : ' needs'} attention.` : 'Your registered labels are on track.'}</h2><p>Every self-check and officer inspection is stored in your company register.</p></div><div className="signal-number"><strong>{dashboard.metrics.complianceRate}%</strong><span>products currently compliant</span></div></div>
    <div className="metric-grid"><Metric label="Registered products" value={String(dashboard.metrics.productCount)} detail="Company-owned catalogue" icon={<Package />} tone="neutral" /><Metric label="Self-checks completed" value={String(dashboard.metrics.inspectionCount)} detail="Persisted inspections" icon={<ClipboardCheck />} tone="positive" /><Metric label="Open flagged cases" value={String(dashboard.metrics.openCases)} detail="Requires review" icon={<AlertTriangle />} tone="alert" /><Metric label="Compliance rate" value={`${dashboard.metrics.complianceRate}%`} detail="Passing products" icon={<ShieldCheck />} tone="positive" /></div>
    <div className="section-grid"><section className="panel"><PanelHeading eyebrow="RECENT ACTIVITY" title="Your compliance register" /><div className="notification-panel">{recent.length ? recent.map((inspection) => <button className="notification-row action-row" key={inspection.id} onClick={() => setSelected(inspection)}><span className={`notification-symbol ${inspection.status === 'Compliant' ? 'info' : 'warning'}`}>{inspection.status === 'Compliant' ? <Check size={17} /> : <AlertTriangle size={17} />}</span><div><b>{inspection.status === 'Compliant' ? 'Check passed' : 'Action required'} · {inspection.product}</b><p>{inspection.summary?.passed ?? 0} of {inspection.summary?.total ?? inspection.checks.length} declarations passed</p><small>{new Date(inspection.createdAt).toLocaleString('en-IN')}</small></div><ChevronRight size={16} /></button>) : <p className="company-reports-empty">No inspections yet. Run your first self-check.</p>}</div></section><section className="panel"><PanelHeading eyebrow="DECLARATION WATCH" title="Most frequent failures" /><div className="flag-list">{analytics.failures.length ? analytics.failures.slice(0, 4).map((item) => <div className="flag-row" key={item.label}><div className="flag-icon"><AlertTriangle size={15} /></div><div><b>{item.label}</b><small>{item.value} failed check{item.value > 1 ? 's' : ''}</small></div><strong>{item.value}</strong></div>) : <p className="company-reports-empty">No declaration failures recorded.</p>}</div></section></div>
    <div className="section-grid"><section className="panel chart-panel"><PanelHeading eyebrow="LAST SIX WEEKS" title="Compliance trend" /><ResponsiveContainer width="100%" height={220}><BarChart data={analytics.trend}><CartesianGrid vertical={false} stroke="#e7e5dc" /><XAxis dataKey="week" axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="value" fill="#e5a93d" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></section><section className="panel"><PanelHeading eyebrow="FLAGGED PRODUCTS" title="Officer inspections" />{dashboard.flagged.length ? dashboard.flagged.slice(0, 4).map((inspection) => <div className="catalogue-row" key={inspection.id}><div><b>{inspection.product}</b><small>{inspection.checks.filter((check) => !check.isCompliant).map((check) => `${check.label} · ${check.ruleSection}`).join(', ')}</small></div><button className="button ghost" onClick={() => { setResubmitProductId(inspection.productId ?? ''); setScreen('scan'); }}>Resubmit <Upload size={14} /></button></div>) : <p className="company-reports-empty">No officer flags for your products.</p>}</section></div>
    <CompanyReportList user={user} /><section className="panel notification-panel"><PanelHeading eyebrow="NOTIFICATIONS" title="Company updates" />{dashboard.notifications.slice(0, 4).map((item) => <div className="notification-row" key={item.id}><span className="notification-symbol warning"><Bell size={17} /></span><div><b>{item.title}</b><p>{item.text}</p><small>{item.when}</small></div></div>)}</section>
  </section></Shell>;
}

function Shell({ user, onLogout, active, onNavigate, children }: { user: User; onLogout: () => void; active: string; onNavigate: (screen: 'home' | 'products' | 'scan') => void; children: React.ReactNode }) { return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={21} /></div><div><strong>metro-check</strong><span>LEGAL METROLOGY / INDIA</span></div></div><div className="workspace-switcher"><span className="avatar small">{user.name.slice(0, 2).toUpperCase()}</span><div><b>{user.name}</b><small>Company account</small></div></div><nav><button className={`nav-item ${active === 'home' ? 'active' : ''}`} onClick={() => onNavigate('home')}><LayoutDashboard size={18} /><span>Company dashboard</span></button><button className={`nav-item ${active === 'products' ? 'active' : ''}`} onClick={() => onNavigate('products')}><Package size={18} /><span>Product register</span></button><button className={`nav-item ${active === 'scan' ? 'active' : ''}`} onClick={() => onNavigate('scan')}><ClipboardCheck size={18} /><span>New self-check</span></button><button className="nav-item" onClick={onLogout}><ArrowUpRight size={18} /><span>Sign out</span></button></nav></aside><main className="main-content"><header className="topbar"><div className="crumb"><span>Metro-Check</span><ChevronRight size={14} /><b>Company dashboard</b></div><div className="top-actions"><Bell size={18} /><div className="avatar">{user.name.slice(0, 2).toUpperCase()}</div></div></header><div className="page-wrap">{children}</div></main></div>; }
function PanelHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="panel-heading"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div></div>; }
function Metric({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: React.ReactNode; tone: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function InspectionResult({ inspection, onClose }: { inspection: Inspection; onClose: () => void }) { return <section className={`result-banner ${inspection.status === 'Compliant' ? 'result-good' : 'result-bad'}`}><div className="result-icon">{inspection.status === 'Compliant' ? <Check size={27} /> : <AlertTriangle size={27} />}</div><div><span className="eyebrow">SELF-CHECK RESULT / {inspection.id}</span><h2>{inspection.status}</h2><p>{inspection.summary?.passed ?? 0} of {inspection.summary?.total ?? inspection.checks.length} declarations passed.</p>{inspection.checks.map((check) => <small className="result-check" key={check.fieldName}>{check.isCompliant ? 'PASS' : 'FAIL'} · {check.label}: {check.detectedValue ?? 'Not detected'} · {check.ruleSection}</small>)}</div><button className="button ghost" onClick={onClose}>Close</button></section>; }
