import { useEffect, useState } from 'react';
import { AlertTriangle, Check, Package, Plus } from 'lucide-react';

type Product = { id: string; name: string; category: string; companyId: string; status: string; declaredMrp?: number; declaredNetQuantity?: number; declaredNetUnit?: string; manufacturerDetails?: string; consumerCareDetails?: string };
type Company = { orgId: string; token?: string };
export default function MatchingProductCatalog({ user }: { user?: Company }) {
  const [products, setProducts] = useState<Product[]>([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = () => fetch('/api/products', { headers: { Authorization: `Bearer ${user?.token ?? localStorage.getItem('metro-check-token') ?? ''}` } }).then((response) => response.json()).then(setProducts).catch(() => setError('Unable to load products')); useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { ...Object.fromEntries(form.entries()), companyId: user?.orgId }; try { const response = await fetch('/api/products', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${user?.token ?? localStorage.getItem('metro-check-token') ?? ''}` }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setMessage('Product registered with official declaration values.'); setShowForm(false); event.currentTarget.reset(); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to register product'); } };
  return <section className="page"><div className="page-heading"><div><span className="eyebrow">COMPANY REGISTRY</span><h1>Product register</h1></div><button className="button primary" onClick={() => setShowForm((value) => !value)}><Plus size={17} /> Register product</button></div>{error && <div className="error-banner"><AlertTriangle size={16} /> {error}</div>}{message && <div className="success-banner"><Check size={16} /> {message}</div>}{showForm && <form className="panel product-form matching-product-form" onSubmit={submit}><div className="form-heading"><span className="eyebrow">OFFICIAL DECLARATIONS</span><h3>Register values used for label comparison</h3></div><label>Product name<input name="name" required /></label><label>Category<input name="category" required /></label><label>Declared MRP (Rs.)<input name="declaredMrp" type="number" min="0" step="0.01" /></label><label>Net quantity<input name="declaredNetQuantity" type="number" min="0" step="0.01" /></label><label>Net unit<select name="declaredNetUnit"><option value="">Not registered</option><option>g</option><option>kg</option><option>ml</option><option>l</option></select></label><label>Manufacturer / packer name & address<input name="manufacturerDetails" /></label><label>Consumer care phone or email<input name="consumerCareDetails" /></label><div className="product-form-actions"><button type="submit" className="button primary">Save registered product <Check size={16} /></button></div></form>}<section className="panel"><div className="catalogue">{products.map((product) => <div className="catalogue-row" key={product.id}><span className="product-thumb"><Package size={19} /></span><div><b>{product.name}</b><small>{product.category} · MRP {product.declaredMrp ?? 'not registered'} · Net {product.declaredNetQuantity ? `${product.declaredNetQuantity} ${product.declaredNetUnit}` : 'not registered'}</small></div><span className="mono">{product.id}</span></div>)}</div></section></section>;
}
