import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, ArrowUpRight, Camera, Check, FileText, ShieldCheck, Upload } from 'lucide-react';

type Product = { id: string; name: string; category: string; companyId: string };

export default function ProductAwareScan({ onComplete }: { onComplete: (inspection: any) => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [productId, setProductId] = useState(''); const [files, setFiles] = useState<File[]>([]); const [error, setError] = useState(''); const [processing, setProcessing] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { fetch('/api/products').then((response) => response.json()).then(setProducts).catch(() => setError('Unable to load registered products')); }, []);
  const submit = async () => { setProcessing(true); setError(''); const form = new FormData(); files.forEach((file) => form.append('images', file)); if (productId) form.append('productId', productId); try { const response = await fetch('/api/scan', { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('metro-check-token') ?? ''}` }, body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? 'Scan failed'); onComplete(body); } catch (scanError) { setError(scanError instanceof Error ? scanError.message : 'Scan failed'); } finally { setProcessing(false); } };
  return <section className="page"><div className="page-heading"><div><span className="eyebrow">OFFICER WORKFLOW / STEP 01</span><h1>Inspect a packaged commodity.</h1></div></div><div className="scanner-layout"><div className="scanner-card"><div className="scanner-top"><div><span className="eyebrow">LABEL CAPTURE</span><h2>Capture both display panels</h2><p>Select a registered product to compare its official declarations, or leave it unlinked for presence checks only.</p></div><Camera size={28} /></div>{error && <div className="error-banner"><AlertTriangle size={16} /> {error}</div>}<label className="product-select-label">Registered product (optional)<select value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">No registered product - presence checks only</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name} · {product.category}</option>)}</select></label><div className={`drop-zone ${files.length ? 'has-files' : ''}`} onClick={() => inputRef.current?.click()}><input ref={inputRef} type="file" accept="image/*" multiple hidden onChange={(event) => setFiles(Array.from(event.target.files ?? []))} />{files.length ? <><div className="upload-success"><Check size={22} /></div><h3>{files.length} image{files.length > 1 ? 's' : ''} ready</h3><p>{files.map((file) => file.name).join(' · ')}</p></> : <><div className="upload-icon"><Upload size={23} /></div><h3>Drop label images here</h3><p>JPG, PNG up to 10 MB</p><button type="button" className="button secondary"><Camera size={17} /> Choose label images</button></>}</div></div><aside className="scan-aside"><span className="eyebrow">MATCHING LAYER</span><h3>{productId ? 'Official values will be compared' : 'Presence checks only'}</h3><div className="legal-note"><FileText size={18} /><p>{productId ? 'MRP, quantity, manufacturer, and consumer care are compared. Date marking remains batch-specific.' : 'Link a registered product when official declaration values are available.'}</p></div><div className="legal-note"><ShieldCheck size={18} /><p>Original uploaded labels are attached automatically to the inspection report.</p></div></aside></div><div className="scan-footer"><span><ShieldCheck size={16} /> Evidence is encrypted and audit logged</span><button className="button primary" disabled={!files.length || processing} onClick={submit}>{processing ? 'Checking label...' : 'Run compliance check'} <ArrowUpRight size={17} /></button></div></section>;
}
